# Generated by Django 5.2.17 on 2026-09-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettier',
            name='sold_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
